### ISSUE TITLE
esy install fails

### ISSUE THREAD

**Issue by davesnx** [bryphe/revery-quick-start#75]
Hey,

This error happened after cloning and ran esy. It is something that I could solve in my end?

```
info esy 0.6.0 (using package.json)
.... fetching revery@github:revery-ui/revery#2fdee68esy: internal error, uncaught exception:
     Unix.Unix_error(Unix.ENOTEMPTY, "rename", "/Users/davesnx/dev/github/teamodoro/_esy/default/tmp/esy-d2e17c")
     Raised at file "esy-lib/RunAsync.re", line 13, characters 2-51
     Re-raised at file "esy-lib/RunAsync.re", line 13, characters 2-51
     Re-raised at file "src/core/lwt.ml", line 2999, characters 20-29
     Called from file "src/unix/lwt_main.ml", line 26, characters 8-18
     Called from file "esy-lib/Cli.re", line 263, characters 9-28
     Called from file "cmdliner_term.ml", line 25, characters 19-24
     Called from file "cmdliner.ml", line 25, characters 27-34
     Called from file "cmdliner.ml", line 116, characters 32-39
```

Using
esy 0.6.0
Revery: revery-ui/revery#2fdee68

**Comment by glennsl** [comment]
This is an error usually caused by another previous error aborting the previous build. Revove `_esy` and try again. If the original problem wasn't transient it should happen again and give you an error message to troubleshoot with.

On macOS this is often caused by hitting an open file limit which can be increased by running `ulimit -Sn 4096`

**Comment by davesnx** [comment]
Appeared the error of too many files opened after the clean 👍
